### ISSUE TITLE
not support jdk8?

### ISSUE THREAD

**Issue by clickear** [lgp547/any-door-plugin#1]
problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: io/github/lgp547/anydoor/autoconfig/AnyDoorAutoConfiguration has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by lgp547** [comment]
下一个版本支持

**Comment by lgp547** [comment]
https://github.com/lgp547/any-door-plugin/commit/f862a0c23e17ecab5b9be7faa622b9387d4ac1d8
