### ISSUE TITLE
idea2022.3.2安装完插件后，并没有Settings AnyDoor这个配置项

### ISSUE THREAD

**Issue by meiMingle** [lgp547/any-door-plugin#2]
![image](https://user-images.githubusercontent.com/39942874/216877780-4206dcaf-41bd-4e9e-82aa-746f4bb3213d.png)

**Comment by lgp547** [comment]
最新版本调整了位置，文档未更新

![image](https://user-images.githubusercontent.com/51388510/217119079-a52a7d03-2386-45a9-b0bc-ebacfa7dafee.png)
