### ISSUE TITLE
在完全离线的环境中Any Door不起作用

### ISSUE THREAD

**Issue by meiMingle** [lgp547/any-door-plugin#3]
Idea 2022.3.2   AnyDoor 1.0.4
具体表现为：
1.在设置里点击`Try imprt jars to RunMoudle`按钮毫无反应，并且窗口冻结无法点击任何其他按钮。
2.大约20s左右，Noticfication窗口出现错误通知，如下
![2023-02-07 142711](https://user-images.githubusercontent.com/39942874/217166993-9169f83f-56a9-45ce-b051-86d014fb0958.png)
3启动项目后，在目标方法上执行`Open AnyDoor`,目标方法并没有执行（日志没输出，也没进断点）

**Comment by lgp547** [comment]
是的，在点击按钮会触发检测本地的maven是否有any-door的jar包，若没有会主动的进行下载（访问maven中央仓库，需要翻墙）。

额外的解决方式：主动的把对应jar包下载到本地的maven仓库里。

像我的仓库地址是 /Users/lgp/.m2/repository 下载好后的jar包会在下面的路径 /Users/lgp/.m2/repository/io/github/lgp547/any-door/0.0.5

**Comment by meiMingle** [comment]
感谢指导，成功啦
