### ISSUE TITLE
Main class RunMoudle name选项可以优化一下

### ISSUE THREAD

**Issue by meiMingle** [lgp547/any-door-plugin#4]
在一个由许多子模块的项目中（超过200个）找到 RunMoudle有些困。建议将这个下拉列表按照字母排序或者加一个搜索框

**Comment by lgp547** [comment]
这个功能不会优先处理，因为新版本已经支持主动填充所在的 RunMoudle 了。
目前正在开发主动的处理 runPort 的填充，最终实现使用者无需配置，直接启动项目即可。

期待你的贡献！

**Comment by lgp547** [comment]
已增加了排序，搜索功能暂不做，后续看看情况是否增加
