### ISSUE TITLE
与xrebel一起使用可能会有问题

### ISSUE THREAD

**Issue by meiMingle** [lgp547/any-door-plugin#5]
有时候在any-door 和xrebel一起启动的时候，通过any-door调用方法时，xrebel无法收集到调用栈信息和SQL信息。目前这个问题还不能稳定复现，先在这记录，等能够稳定复现我再附上具体操作

![3dab1d4c0020d2be682ce1382dc7bef9](https://user-images.githubusercontent.com/39942874/217445164-b2af6ce7-0f67-49a9-b63e-9bbdc1d432c0.jpg)

**Comment by meiMingle** [comment]
https://manuals.jrebel.com/xrebel/use/advanced.html#asynchronous-tracing
参照xrebel的文档，可能的原因是，Anydoor使用异步的方式执行目标方法，而xrebel默认情况下对超过10s的异步任务不再继续跟踪。在对目标方法打断点进行调试的时候通常时间总是超过10s。建议添加可选的配置，让用户决定是否使用异步的方式。
临时解决办法 : 可以使用 JVM 属性控制xrebel跟踪异步方法的上限时间-Dxrebel.async.wait_timeout.sec=300

**Comment by lgp547** [comment]
已收到，实际是有支持同步执行代码，可以开放出来
