### ISSUE TITLE
Attach 模式下，每次调用idea都会收到到一个异常通知

### ISSUE THREAD

**Issue by meiMingle** [lgp547/any-door-plugin#8]
idea2022.3.2
anydoor-plugin 1.0.7   
any-door.jar   0.0.10
奇怪的是，方法执行的过程中没有异常抛出，控制台没有错误日志，idea的日志文件中也没有记录异常
![image](https://user-images.githubusercontent.com/39942874/220077891-e30f485c-4c8a-44bf-95c2-8dd4c0becd99.png)

**Comment by lgp547** [comment]
有点奇怪，得看看。其他项目使用是否有问题

**Comment by meiMingle** [comment]
> 有点奇怪，得看看。其他项目使用是否有问题

其他项目也是如此

**Comment by lgp547** [comment]
我这里是部分项目

**Comment by lgp547** [comment]
嫌它烦人就先用回http的

**Comment by lgp547** [comment]
jdk版本不兼容问题，插件用的是11版本，运行项目是8的话就会有这个异常。统一为8的吧

**Comment by meiMingle** [comment]
搜索了一圈，找到了arthas的处理，可以参考优化一下
https://github.com/alibaba/arthas/blob/master/core/src/main/java/com/taobao/arthas/core/Arthas.java

**Comment by lgp547** [comment]
https://github.com/lgp547/any-door-plugin/commit/b7f8119dce23e9a5d4cda8accde1934e8734441e
